"""
Abrir y cerrar aplicaciones (4.8): `open_app` (🟢, sin plan) y `close_app` (🔴, plan y
«Permitir»). Las dos nacen apagadas.

Lo que haría daño si fallase: que se abriera una consola o un intérprete (con otro nombre:
medido en mi PC, Git CMD, MSYS2, Python, IDLE o Node.js), una herramienta de
administración, un script o un programa suelto; un archivo o una carpeta fuera de lo
permitido; una dirección que no es una página; o que cerrar se llevara un proceso del
sistema, de Morgan o de otra persona.
"""

import struct
import subprocess
import sys
import time

import pytest

from src.agente import aplicaciones, aviso
from src.agente.politica import DE_APLICACIONES, Politica
from tests.test_agente_escritura import papelera, pc, preguntas, sistema_de_mentira  # noqa: F401


def lnk(destino: str, unicode: bool = True) -> bytes:
    """Un acceso directo mínimo (MS-SHLLINK) con LinkInfo y la ruta del destino."""
    cabecera = struct.pack("<I16sI", 0x4C, b"\x01\x14\x02\x00\x00\x00\x00\x00\xc0\x00\x00\x00\x00\x00\x00\x46",
                           0x02) + b"\x00" * (0x4C - 24)
    ansi = destino.encode("latin-1", errors="replace") + b"\x00"
    uni = destino.encode("utf-16-le") + b"\x00\x00"
    tam_cab = 0x24 if unicode else 0x1C
    desp_ansi = tam_cab
    desp_uni = desp_ansi + len(ansi)
    info = struct.pack("<IIIIIII", 0, tam_cab, 1, 0, desp_ansi, 0, 0)
    if unicode:
        info += struct.pack("<II", 0, desp_uni)
    cuerpo = info + ansi + (uni if unicode else b"")
    cuerpo = struct.pack("<I", len(cuerpo)) + cuerpo[4:]
    return cabecera + cuerpo


#: Del catálogo de Windows (`Get-StartApps` en mi PC, 141 apps): las que no tienen acceso `.lnk`.
CATALOGO = [
    ("Calculadora", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"),
    ("Spotify", "SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify"),
    ("Hollow Knight", "steam://rungameid/367520"),
    ("Fortnite", "com.epicgames.launcher://apps/fn%3A4fe75bbc%3AFortnite?action=launch&silent=true"),
    ("Explorador de archivos", "Microsoft.Windows.Explorer"),
    ("Mapa de caracteres", "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\charmap.exe"),
    ("Word", "Microsoft.Office.WINWORD.EXE.15"),                     # también tiene acceso: gana el acceso
    # Lo que no se abre nunca:
    ("Símbolo del sistema", "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\cmd.exe"),
    ("Servicios", "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\services.msc"),
    ("Configuración del sistema", "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\msconfig.exe"),
    ("Diagnóstico de memoria de Windows", "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\MdSched.exe"),
    ("Editor del Registro", "{F38BF404-1D43-42F2-9305-67DE0B28FC23}\\regedit.exe"),
    ("Programador de tareas", "Microsoft.AutoGenerated.{19EC9782-4EDE-C19F-08F2-3A612CECFE6B}"),
    ("Panel de control", "Microsoft.Windows.ControlPanel"),
    ("Abrir", "Microsoft.Windows.Shell.RunDialog"),
    ("Consola rara", "Microsoft.WindowsTerminal_8wekyb3d8bbwe!App"),
    ("Gestor de versiones", "PythonSoftwareFoundation.PythonManager_3847v3x7pw1km!Py.Manager"),
    ("Flujos", "Microsoft.PowerAutomateDesktop_8wekyb3d8bbwe!PAD.Console"),
    ("Ayuda de Java", "http://java.com/help"),
    ("Diagnóstico", "ms-msdt:/id PCWDiagnostic"),
    ("Juego raro", "steam://run/367520//-dev"),
    ("Herramienta", r"{6D809377-6AF0-444B-8957-A3773F02200E}\Raro\python.exe"),
    # Un nombre de consola en una familia que no lo dice: manda el nombre.
    ("PowerShell", "Contoso.ShellPlus_abcdefghjkmnp!App"),
]


@pytest.fixture
def menu(tmp_path, monkeypatch, pc):
    """Un menú Inicio de mentira, las dos capacidades encendidas y `_abrir` apuntado."""
    base = tmp_path / "Menu"
    accesos = {
        "Visual Studio Code/Visual Studio Code.lnk": r"C:\Users\ana\AppData\Local\Programs\Microsoft VS Code\Code.exe",
        "Word.lnk": r"C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE",
        "Mi editor.lnk": r"C:\Windows\System32\cmd.exe",
        "Windows PowerShell/Windows PowerShell.lnk": r"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe",
        "Windows PowerShell/Windows PowerShell ISE.lnk": r"C:\Windows\System32\WindowsPowerShell\v1.0\powershell_ise.exe",
        "Git/Git CMD.lnk": r"C:\Program Files\Git\git-cmd.exe",
        "Herramientas raras/Consola.lnk": r"C:\msys64\ucrt64.exe",
        "Administrative Tools/Task Scheduler.lnk": r"C:\Windows\System32\taskschd.msc",
        "Startup/Morgan agente local.lnk": r"C:\Users\ana\morgan.cmd",
        "Utilidades/Script.lnk": r"C:\Users\ana\limpiar.ps1",
        "Excel.lnk": r"C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE",
        "Excel Viewer.lnk": r"C:\Program Files\Viewer\xlview.exe",
    }
    # De la carpeta de herramientas, con un destino que por sí solo no dice nada.
    accesos["Administrative Tools/Resource Monitor.lnk"] = r"C:\Windows\System32\perfmon.exe"
    for relativa, destino in accesos.items():
        ruta = base / relativa
        ruta.parent.mkdir(parents=True, exist_ok=True)
        ruta.write_bytes(lnk(destino))
    # Y uno cuyo destino no se puede leer (en mi PC, varios): decide el nombre.
    (base / "Command Prompt.lnk").write_bytes(b"ilegible")
    monkeypatch.setattr(aplicaciones, "carpetas_del_menu", lambda: [base])
    # El catálogo de apps de Windows (5.3), de mentira: lo que sale en un PC de verdad.
    monkeypatch.setattr(aplicaciones, "catalogo_de_windows", lambda: [dict(nombre=n, id=i) for n, i in CATALOGO])
    abiertas = []
    monkeypatch.setattr(aplicaciones, "_abrir", lambda que, argumentos="": abiertas.append((str(que), argumentos)))
    politica = Politica.cargar()
    for c in DE_APLICACIONES:
        politica.capacidades[c] = True
    politica.guardar()
    return {"abiertas": abiertas, "base": base, **pc}


class TestNacen:
    def test_apagadas(self):
        politica = Politica()
        assert not politica.capacidades["open_app"] and not politica.capacidades["close_app"]

    def test_apagada_no_abre(self, pc):
        r = aplicaciones.open_app("url", url="https://example.com")
        assert not r["success"] and r["motivo"] == "capacidad_apagada"


class TestElAcceso:
    @pytest.mark.parametrize("unicode", [True, False])
    def test_lee_el_destino(self, tmp_path, unicode):
        ruta = tmp_path / "a.lnk"
        ruta.write_bytes(lnk(r"C:\Program Files\App\app.exe", unicode))
        assert aplicaciones.destino_del_acceso(ruta) == r"C:\Program Files\App\app.exe"

    def test_uno_roto_no_revienta(self, tmp_path):
        ruta = tmp_path / "roto.lnk"
        ruta.write_bytes(b"no es un acceso")
        assert aplicaciones.destino_del_acceso(ruta) is None


class TestAbrirUnaAplicacion:
    def test_listar_sin_las_prohibidas(self, menu):
        lista = aplicaciones.open_app("listar")["data"]["aplicaciones"]
        # Los accesos que se pueden abrir, y del catálogo (5.3) las que no tienen acceso.
        assert sorted(lista) == ["Calculadora", "Excel", "Excel Viewer", "Explorador de archivos", "Fortnite",
                                 "Hollow Knight", "Mapa de caracteres", "Spotify", "Visual Studio Code", "Word"]

    def test_abre_una_instalada(self, menu):
        r = aplicaciones.open_app("aplicacion", nombre="visual studio code")
        assert r["success"], r
        assert menu["abiertas"][0][0].endswith("Visual Studio Code.lnk")

    def test_la_exacta_gana_a_las_parecidas(self, menu):
        assert aplicaciones.open_app("aplicacion", nombre="Excel")["success"]
        assert menu["abiertas"][0][0].endswith("Excel.lnk")

    def test_si_hay_varias_pregunta(self, menu):
        r = aplicaciones.open_app("aplicacion", nombre="exc")
        assert not r["success"] and r["motivo"] == "ambigua" and not menu["abiertas"]

    def test_una_que_no_esta(self, menu):
        assert aplicaciones.open_app("aplicacion", nombre="Photoshop")["motivo"] == "no_instalada"

    @pytest.mark.parametrize("nombre", ["Windows PowerShell", "Mi editor", "Git CMD", "Consola", "Script"])
    def test_nunca_una_consola_ni_un_script(self, menu, nombre):
        r = aplicaciones.open_app("aplicacion", nombre=nombre)
        assert not r["success"] and r["motivo"] == "prohibida", r
        assert not menu["abiertas"]

    @pytest.mark.parametrize("nombre", ["Task Scheduler", "Morgan agente local", "Resource Monitor",
                                        "Command Prompt"])
    def test_ni_herramientas_del_sistema_ni_morgan(self, menu, nombre):
        assert not aplicaciones.open_app("aplicacion", nombre=nombre)["success"]
        assert not menu["abiertas"]

    def test_con_una_carpeta_permitida(self, menu):
        r = aplicaciones.open_app("aplicacion", nombre="Visual Studio Code", path=str(menu["notas"]))
        assert r["success"], r
        assert menu["abiertas"][0][1] == f'"{menu["notas"]}"'

    def test_con_una_ruta_de_fuera_no(self, menu):
        r = aplicaciones.open_app("aplicacion", nombre="Visual Studio Code", path=str(menu["fuera"]))
        assert not r["success"] and not menu["abiertas"]

    def test_con_un_programa_no(self, menu):
        (menu["notas"] / "x.bat").write_text("echo", encoding="utf-8")
        r = aplicaciones.open_app("aplicacion", nombre="Word", path=str(menu["notas"] / "x.bat"))
        assert not r["success"] and not menu["abiertas"]


class TestAbrirLoDemas:
    def test_un_archivo_con_su_programa(self, menu):
        (menu["notas"] / "factura.pdf").write_bytes(b"%PDF")
        assert aplicaciones.open_app("archivo", path=str(menu["notas"] / "factura.pdf"))["success"]
        assert menu["abiertas"][0][0].endswith("factura.pdf")

    @pytest.mark.parametrize("nombre", ["virus.exe", "a.bat", "a.ps1", "atajo.lnk", "a.vbs", "a.hta", "a.url"])
    def test_nunca_uno_que_se_ejecuta(self, menu, nombre):
        (menu["notas"] / nombre).write_bytes(b"x")
        r = aplicaciones.open_app("archivo", path=str(menu["notas"] / nombre))
        assert not r["success"] and not menu["abiertas"]

    def test_ni_de_fuera_ni_credenciales(self, menu):
        (menu["notas"] / ".env").write_text("K=1", encoding="utf-8")
        assert not aplicaciones.open_app("archivo", path=str(menu["fuera"] / "ajeno.txt"))["success"]
        assert not aplicaciones.open_app("archivo", path=str(menu["notas"] / ".env"))["success"]
        assert not aplicaciones.open_app("archivo", path="")["success"]
        assert not menu["abiertas"]

    def test_una_carpeta(self, menu):
        assert aplicaciones.open_app("carpeta", path=str(menu["notas"]))["success"]
        assert not aplicaciones.open_app("carpeta", path=str(menu["fuera"]))["success"]
        assert len(menu["abiertas"]) == 1

    @pytest.mark.parametrize("url", ["https://morgan.example/a?b=1", "http://example.com"])
    def test_una_pagina(self, menu, url):
        assert aplicaciones.open_app("url", url=url)["success"]

    @pytest.mark.parametrize("url", ["javascript:alert(1)", "file:///C:/Windows/win.ini", "ms-settings:",
                                     "https://ana:clave@example.com", "http://", "https://a.com/\"x"])
    def test_lo_que_no_es_una_pagina(self, menu, url):
        assert not aplicaciones.open_app("url", url=url)["success"]
        assert not menu["abiertas"]

    def test_con_confirmar_abrir_se_pregunta(self, menu):
        politica = Politica.cargar()
        politica.confirmar["abrir"] = True
        politica.guardar()
        menu["preguntas"]["respuesta"]["valor"] = "rechazada"
        r = aplicaciones.open_app("url", url="https://example.com")
        assert not r["success"] and r["motivo"] == "no_confirmada"
        assert len(menu["preguntas"]["hechas"]) == 1 and not menu["abiertas"]


@pytest.fixture
def durmiente():
    p = subprocess.Popen([sys.executable, "-c", "import time; time.sleep(60)"])
    time.sleep(0.5)
    yield p
    p.kill()


class TestCerrar:
    def _encender(self):
        politica = Politica.cargar()
        politica.capacidades["close_app"] = True
        politica.guardar()

    def test_pid_y_nombre_tienen_que_coincidir(self, pc, durmiente):
        self._encender()
        r = aplicaciones.close_app(pid=durmiente.pid, name="notepad.exe")
        assert not r["success"] and r["motivo"] == "no_coincide" and durmiente.poll() is None

    def test_sin_ventana_no_se_cierra_sin_forzar(self, pc, durmiente, monkeypatch):
        self._encender()
        monkeypatch.setattr(aplicaciones, "_ventanas_de", lambda pid: [])
        import psutil

        nombre = psutil.Process(durmiente.pid).name()
        r = aplicaciones.close_app(pid=durmiente.pid, name=nombre)
        assert not r["success"] and r["motivo"] == "sigue_abierto" and durmiente.poll() is None
        assert pc["preguntas"]["hechas"], "cerrar se confirma en el PC"

    def test_forzando_si(self, pc, durmiente, monkeypatch):
        self._encender()
        monkeypatch.setattr(aplicaciones, "_ventanas_de", lambda pid: [])
        import psutil

        nombre = psutil.Process(durmiente.pid).name()
        r = aplicaciones.close_app(pid=durmiente.pid, name=nombre, forzar=True)
        assert r["success"] and r["data"]["forzado"]
        durmiente.wait(5)

    def test_con_un_no_no_se_toca(self, pc, durmiente):
        self._encender()
        pc["preguntas"]["respuesta"]["valor"] = "rechazada"
        import psutil

        r = aplicaciones.close_app(pid=durmiente.pid, name=psutil.Process(durmiente.pid).name(), forzar=True)
        assert not r["success"] and durmiente.poll() is None

    def test_ni_el_sistema(self, pc):
        self._encender()
        r = aplicaciones.close_app(pid=4, name="System")
        assert not r["success"]


class TestEnLaNube:
    def test_abrir_verde_y_cerrar_rojo(self):
        from src.canal.herramientas import AplicacionDelEquipo, herramientas_del_equipo

        h = {x.name: x for x in herramientas_del_equipo() if isinstance(x, AplicacionDelEquipo)}
        assert h["open_app"].permission_level == "safe" and not h["open_app"].exige_plan
        assert h["close_app"].permission_level == "critical" and h["close_app"].exige_plan

    def test_una_pagina_tras_leer_el_pc_pasa_por_la_fuga(self):
        from src.agent import fuga

        assert fuga.SALEN_A_INTERNET["open_app"] == "url"
        assert "open_app" in fuga.DEL_PC


class TestLoQueMidioElModelo:
    def test_powershell_con_variantes_no_pregunta_cual(self, menu):
        """Medido con el modelo real (4.8): «abre PowerShell» encontraba varias, contestaba
        «di cuál» y el modelo se lo preguntaba a la persona, como si alguna se pudiera abrir."""
        r = aplicaciones.open_app("aplicacion", nombre="powershell")
        assert not r["success"] and r["motivo"] == "prohibida" and not menu["abiertas"]


class TestElCatalogoDeWindows:
    """5.3: las apps sin acceso `.lnk` (la Store, las integradas, los juegos). Medido en mi PC:
    con solo los accesos, 79 de 141 no se podían abrir (Calculadora, Spotify, Teams…)."""

    def test_abre_una_de_la_store_por_su_identificador(self, menu):
        r = aplicaciones.open_app(accion="aplicacion", nombre="calculadora")
        assert r["success"], r
        assert menu["abiertas"] == [("shell:AppsFolder\\Microsoft.WindowsCalculator_8wekyb3d8bbwe!App", "")]

    @pytest.mark.parametrize("nombre", ["Spotify", "Hollow Knight", "Fortnite", "Explorador de archivos",
                                        "Mapa de caracteres"])
    def test_las_que_si(self, menu, nombre):
        assert aplicaciones.open_app(accion="aplicacion", nombre=nombre)["success"]

    @pytest.mark.parametrize("nombre", ["Símbolo del sistema", "Servicios", "Configuración del sistema",
                                        "Diagnóstico de memoria", "Editor del Registro", "Programador de tareas",
                                        "Panel de control", "Abrir", "Consola rara", "Gestor de versiones", "Flujos",
                                        "Ayuda de Java", "Diagnóstico", "Juego raro", "Herramienta"])
    def test_lo_del_sistema_las_consolas_y_los_protocolos_no(self, menu, nombre):
        r = aplicaciones.open_app(accion="aplicacion", nombre=nombre)
        assert not r["success"] and r["motivo"] in ("prohibida", "no_instalada"), r
        assert menu["abiertas"] == []

    def test_listar_las_ensena_sin_las_prohibidas(self, menu):
        lista = aplicaciones.open_app(accion="listar")["data"]["aplicaciones"]
        assert {"Calculadora", "Spotify", "Hollow Knight"} <= set(lista)
        assert not {"Servicios", "Panel de control", "Consola rara", "Flujos", "Ayuda de Java"} & set(lista)

    def test_si_esta_en_los_dos_gana_el_acceso(self, menu):
        assert aplicaciones.open_app(accion="aplicacion", nombre="Word")["success"]
        assert menu["abiertas"][0][0].endswith("Word.lnk")

    def test_las_del_catalogo_no_llevan_una_ruta(self, menu):
        # Aunque la ruta esté permitida: una app de la Store no se abre con argumentos.
        r = aplicaciones.open_app(accion="aplicacion", nombre="Spotify", path=str(menu["notas"]))
        assert not r["success"] and r["motivo"] == "argumentos", r
        assert menu["abiertas"] == []

    def test_un_nombre_de_consola_no_aunque_la_familia_no_lo_diga(self, menu):
        assert aplicaciones.del_catalogo("PowerShell", "Contoso.ShellPlus_abcdefghjkmnp!App")
        r = aplicaciones.open_app(accion="aplicacion", nombre="PowerShell")
        assert not r["success"] and menu["abiertas"] == []

    def test_cada_capa_por_su_lado(self, menu):
        """Dos capas: `todas()` no trae las prohibidas del catálogo, y `_motivo` las rechaza
        aunque llegaran. Rota una, la otra sigue: por eso se prueban por separado."""
        nombres = {a["nombre"] for a in aplicaciones.todas()}
        assert {"Calculadora", "Hollow Knight"} <= nombres
        assert not {"Servicios", "Panel de control", "Consola rara", "Flujos", "Ayuda de Java"} & nombres
        assert aplicaciones._motivo({"nombre": "Servicios", "id": CATALOGO[8][1]})
        assert aplicaciones._motivo({"nombre": "Flujos", "id": CATALOGO[17][1]})
        assert not aplicaciones._motivo({"nombre": "Calculadora", "id": CATALOGO[0][1]})

    def test_si_el_catalogo_falla_quedan_los_accesos(self, menu, monkeypatch):
        monkeypatch.setattr(aplicaciones, "catalogo_de_windows", lambda: [])
        assert aplicaciones.open_app(accion="aplicacion", nombre="Visual Studio Code")["success"]

    @pytest.mark.skipif(sys.platform != "win32", reason="el catálogo es de Windows")
    def test_el_catalogo_de_verdad_se_lee(self):
        """Solo leer (no abre nada): el de este PC, por COM. Las de la Store, que no dependen del
        menú Inicio (estas pruebas llevan APPDATA y ProgramData a una carpeta temporal)."""
        apps = aplicaciones.catalogo_de_windows()
        assert apps and all(a["nombre"] and a["id"] for a in apps)
        empaquetadas = [a for a in apps if aplicaciones._EMPAQUETADA.match(a["id"])]
        assert empaquetadas and any(not aplicaciones.del_catalogo(a["nombre"], a["id"]) for a in empaquetadas)
